# Generated by Django 6.0.6 on 2026-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_contacted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='platform_link',
            field=models.URLField(blank=True),
        ),
    ]
