# Generated by Django 6.0.6 on 2026-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_platform_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('tech', 'Tech'), ('seo', 'SEO')], max_length=20),
        ),
    ]
