# Generated by Django 6.0.6 on 2026-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='questionnaire',
            field=models.TextField(blank=True),
        ),
    ]
