# Generated by Django 6.0.6 on 2026-06-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_contact_no_lead_lead_fb_id_lead_lead_insta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contacted_by',
        ),
    ]
