# Generated by Django 6.0.6 on 2026-06-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
    ]
