# Generated by Django 6.0.6 on 2026-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeature',
            name='clients_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='leads_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='reports_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantfeature',
            name='tasks_module',
            field=models.BooleanField(default=True),
        ),
    ]
