# Generated by Django 6.0.6 on 2026-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantfeature_clients_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeature',
            name='departments_module',
            field=models.BooleanField(default=True),
        ),
    ]
