# Generated by Django 6.0.5 on 2026-06-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('tech', 'Tech'), ('seo', 'SEO')], max_length=20),
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=60)),
                ('academic_level', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('citation_style', models.CharField(blank=True, max_length=20)),
                ('reference_count', models.PositiveIntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_detail', to='clients.client')),
            ],
            options={
                'db_table': 'sales_details',
            },
        ),
        migrations.DeleteModel(
            name='AcademicDetail',
        ),
    ]
