# Generated by Django 6.0.6 on 2026-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_super_admin_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('tech', 'Tech'), ('seo', 'SEO')], max_length=20, null=True),
        ),
    ]
