# Generated by Django 6.0.6 on 2026-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
